version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: smite_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: smite_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smite_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  smite_network:
    driver: bridge
